# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/houstonn/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/houstonn/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
	vendor/houstonn/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
	vendor/houstonn/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
	vendor/houstonn/proprietary/media/Whistle.ogg:system/media/audio/notifications/s_whistle.ogg \
	vendor/houstonn/proprietary/etc/dcm_settings.xml:system/etc/dcm_settings.xml
	

PRODUCT_COPY_FILES += \
    vendor/houstonn/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/houstonn/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/houstonn/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/houstonn/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/houstonn/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/houstonn/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/houstonn/proprietary/bin/efsks:system/bin/efsks \
    vendor/houstonn/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/houstonn/proprietary/bin/ks:system/bin/ks \
    vendor/houstonn/proprietary/bin/mm-audio-send-cal:system/bin/mm-audio-send-cal \
    vendor/houstonn/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/houstonn/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/houstonn/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/houstonn/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/houstonn/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/houstonn/proprietary/bin/qcks:system/bin/qcks \
    vendor/houstonn/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/houstonn/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/houstonn/proprietary/bin/radish:system/bin/radish \
    vendor/houstonn/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/houstonn/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/houstonn/proprietary/bin/thermald:system/bin/thermald \
    vendor/houstonn/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/houstonn/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/houstonn/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/houstonn/proprietary/etc/diag.cfg:system/etc/diag.cfg \
    vendor/houstonn/proprietary/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
    vendor/houstonn/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/houstonn/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/houstonn/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/houstonn/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/houstonn/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/houstonn/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/houstonn/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/houstonn/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/houstonn/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/houstonn/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/houstonn/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/houstonn/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/houstonn/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/houstonn/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/houstonn/proprietary/etc/firmware/wcd9310/wcd9310_anc.bin:system/etc/firmware/wcd9310/wcd9310_anc.bin \
    vendor/houstonn/proprietary/etc/firmware/wcd9310/wcd9310_mbhc.bin:system/etc/firmware/wcd9310/wcd9310_mbhc.bin \
    vendor/houstonn/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/houstonn/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/houstonn/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/houstonn/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/houstonn/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/houstonn/proprietary/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
    vendor/houstonn/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	vendor/houstonn/proprietary/bin/sns_dsps_tc0001:system/bin/sns_dsps_tc0001 \
    vendor/houstonn/proprietary/bin/sns_cm_conc_test:system/bin/sns_cm_conc_test \
	vendor/houstonn/proprietary/lib/libsensor_test.so:system/lib/libsensor_test.so \
    vendor/houstonn/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/houstonn/proprietary/lib/libAKM.so:system/lib/libAKM.so \
    vendor/houstonn/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/houstonn/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/houstonn/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/houstonn/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
    vendor/houstonn/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/houstonn/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
    vendor/houstonn/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/houstonn/proprietary/lib/libcamera_fast_af.so:system/lib/libcamera_fast_af.so \
    vendor/houstonn/proprietary/lib/libchromatix_imx111_default_video.so:system/lib/libchromatix_imx111_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_imx111_preview.so:system/lib/libchromatix_imx111_preview.so \
    vendor/houstonn/proprietary/lib/libchromatix_imx111_zsl.so:system/lib/libchromatix_imx111_zsl.so \
    vendor/houstonn/proprietary/lib/libchromatix_imx119_default_video.so:system/lib/libchromatix_imx119_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_imx119_preview.so:system/lib/libchromatix_imx119_preview.so \
    vendor/houstonn/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/houstonn/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/houstonn/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/houstonn/proprietary/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
    vendor/houstonn/proprietary/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
    vendor/houstonn/proprietary/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
    vendor/houstonn/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/houstonn/proprietary/lib/libchromatix_vx6953_default_video.so:system/lib/libchromatix_vx6953_default_video.so \
    vendor/houstonn/proprietary/lib/libchromatix_vx6953_preview.so:system/lib/libchromatix_vx6953_preview.so \
    vendor/houstonn/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/houstonn/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/houstonn/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/houstonn/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/houstonn/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/houstonn/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/houstonn/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/houstonn/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/houstonn/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/houstonn/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/houstonn/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/houstonn/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/houstonn/proprietary/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
    vendor/houstonn/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/houstonn/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/houstonn/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/houstonn/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/houstonn/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/houstonn/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/houstonn/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/houstonn/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    vendor/houstonn/proprietary/lib/libllvm-arm.so:system/lib/libllvm-arm.so \
    vendor/houstonn/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/houstonn/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/houstonn/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/houstonn/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/houstonn/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/houstonn/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/houstonn/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/houstonn/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/houstonn/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/houstonn/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/houstonn/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/houstonn/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
    vendor/houstonn/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
    vendor/houstonn/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/houstonn/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/houstonn/proprietary/lib/libmorpho_noise_reduction.so:system/lib/libmorpho_noise_reduction.so \
    vendor/houstonn/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/houstonn/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/houstonn/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/houstonn/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/houstonn/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/houstonn/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/houstonn/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/houstonn/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/houstonn/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/houstonn/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/houstonn/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/houstonn/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/houstonn/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/houstonn/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/houstonn/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/houstonn/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/houstonn/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/houstonn/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/houstonn/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/houstonn/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/houstonn/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/houstonn/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/houstonn/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/houstonn/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/houstonn/proprietary/lib/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
    vendor/houstonn/proprietary/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/houstonn/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/houstonn/proprietary/lib/lib_dlb_msd.so:system/lib/lib_dlb_msd.so \
    vendor/houstonn/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/houstonn/proprietary/vendor/firmware/discretix/dxhdcp2.b00:system/vendor/firmware/discretix/dxhdcp2.b00 \
    vendor/houstonn/proprietary/vendor/firmware/discretix/dxhdcp2.b01:system/vendor/firmware/discretix/dxhdcp2.b01 \
    vendor/houstonn/proprietary/vendor/firmware/discretix/dxhdcp2.b02:system/vendor/firmware/discretix/dxhdcp2.b02 \
    vendor/houstonn/proprietary/vendor/firmware/discretix/dxhdcp2.b03:system/vendor/firmware/discretix/dxhdcp2.b03 \
    vendor/houstonn/proprietary/vendor/firmware/discretix/dxhdcp2.mdt:system/vendor/firmware/discretix/dxhdcp2.mdt \
    vendor/houstonn/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/houstonn/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/houstonn/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/houstonn/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/houstonn/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	vendor/houstonn/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/houstonn/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/houstonn/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/houstonn/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/houstonn/proprietary/etc/firmware/wcnss.b05:system/etc/firmware/wcnss.b05 \
    vendor/houstonn/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt